<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.557">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-07-14">

<title>MT5000 Assignment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="MT5000 Quarto Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="MT5000 Quarto Report_files/libs/quarto-html/quarto.js"></script>
<script src="MT5000 Quarto Report_files/libs/quarto-html/popper.min.js"></script>
<script src="MT5000 Quarto Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MT5000 Quarto Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="MT5000 Quarto Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MT5000 Quarto Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MT5000 Quarto Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MT5000 Quarto Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MT5000 Quarto Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MT5000 Assignment</h1>
<p class="subtitle lead">Report on Comparison of COVID-19 in Ireland with 9 Other Countries</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 14, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Author: Chethan Kashyap R</p>
<section id="introduction-and-background" class="level1">
<h1>1. Introduction and Background</h1>
<p>Covid-19 pandemic has caused health uncertainty across the world and it was first detected in Ireland in March 2022. The number of confirmed cases since then has increased significantly and reached 1,697,775 by the end of 2022 (Gagliardi, 2023). In December 2022, the rate of new cases registered was 80 per 100,000 cases, indicating the significantly high prevalence of the Covid-19 pandemic in Ireland (Gagliardi, 2023). However, the severity of this pandemic was even higher in countries like the United States, where approximately 96.8 million confirmed cases were registered by November 2022 (Elflein, 2022). On the other hand, in countries like Cuba (8530), Latvia (6321), Nambia (4090) and Malawi (2686), severity of the Covid-19 pandemic was considerably low, whereas in countries like the United States confirmed death cases reached 1.16 million in 2022 (Elflein, 2023). In this context, on behalf of the ‘National Public Health Emergency Team (NPHET)’ (in the job role of Data Analyst), this study proposes to compare the Covid-19 situation of Ireland and 9 other countries (Cuba, Latvia, Malawi, Montserrat, Namibia, Pitcairn, Timor, Togo and United States) using R programming language in the form of a Quarto Report document.</p>
</section>
<section id="aim-and-objectives" class="level1">
<h1><strong>2. Aim and objectives</strong></h1>
<section id="aim" class="level2">
<h2 class="anchored" data-anchor-id="aim"><strong>2.1 Aim</strong></h2>
<p>The aim of this report is to compare the Irish response to Covid-19 between 2020 and 2022 with 9 other countries (such as Cuba, Latvia, Malawi, Montserrat, Namibia, Pitcairn, Timor, Togo and the United States).</p>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives"><strong>2.2 Objectives</strong></h2>
<ul>
<li><p>To perform data transformation (data cleaning, selection, filtering and summarisation) on the country_data and country_metadata using R</p></li>
<li><p>To develop a world map chart for showing the total new Covid 19 cases across countries</p></li>
<li><p>To develop bar chart for representing total Covid-19 cases across the 10 countries (Ireland and 9 others)</p></li>
<li><p>To create a scatter plot with a linear regression line for COVID-19 Total Deaths vs Total Cases across the 10 countries</p></li>
<li><p>To formulate a time series plot for representing new cases across countries over the periods (2020-2022).</p></li>
</ul>
</section>
</section>
<section id="data-transformation" class="level1">
<h1>3. Data transformation</h1>
<section id="loading-libraries-and-dataset" class="level2">
<h2 class="anchored" data-anchor-id="loading-libraries-and-dataset">3.1 Loading libraries and dataset</h2>
<p>The ‘tidyverse’ library has been used to transform and manipulate both ‘country_data’ and ‘country_metadata’, which has been loaded into R through the use of ‘read.csv(“country_data.csv”, stringsAsFactors = FALSE)’ and read.csv(“country_metadata.csv”, stringsAsFactors = FALSE) functions.</p>
</section>
<section id="data-cleaning-and-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-and-transformation">3.2 Data cleaning and transformation</h2>
<section id="checking-for-null-values-in-country_data" class="level3">
<h3 class="anchored" data-anchor-id="checking-for-null-values-in-country_data">3.2.1 Checking for null values in country_data</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   iso_code          continent           location             date          
 Length:10920       Length:10920       Length:10920       Length:10920      
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
  total_cases         new_cases       new_cases_smoothed  total_deaths      
 Min.   :       1   Min.   :      0   Min.   :     0.0   Min.   :      1.0  
 1st Qu.:    1736   1st Qu.:      0   1st Qu.:     0.1   1st Qu.:    107.8  
 Median :   36994   Median :      0   Median :    18.3   Median :   1331.0  
 Mean   : 5073294   Mean   :   9444   Mean   :  9487.0   Mean   :  75589.1  
 3rd Qu.:  334382   3rd Qu.:      0   3rd Qu.:   444.1   3rd Qu.:   5916.0  
 Max.   :99019493   Max.   :5650933   Max.   :807276.1   Max.   :1079976.0  
 NA's   :1526       NA's   :1         NA's   :51         NA's   :2324       
   new_deaths      new_deaths_smoothed total_cases_per_million
 Min.   :    0.0   Min.   :   0.000    Min.   :     0         
 1st Qu.:    0.0   1st Qu.:   0.000    1st Qu.:  2493         
 Median :    0.0   Median :   0.143    Median : 12560         
 Mean   :  101.8   Mean   : 102.222    Mean   : 68018         
 3rd Qu.:    0.0   3rd Qu.:   4.143    3rd Qu.: 85106         
 Max.   :23312.0   Max.   :3330.286    Max.   :524420         
                   NA's   :50          NA's   :1526           
 new_cases_per_million new_cases_smoothed_per_million total_deaths_per_million
 Min.   :    0.0       Min.   :    0.000              Min.   :   0.003        
 1st Qu.:    0.0       1st Qu.:    0.107              1st Qu.:  34.931        
 Median :    0.0       Median :    4.020              Median : 226.603        
 Mean   :  160.1       Mean   :  160.848              Mean   : 769.290        
 3rd Qu.:    0.0       3rd Qu.:   98.001              3rd Qu.:1390.716        
 Max.   :85106.4       Max.   :12158.055              Max.   :3788.390        
 NA's   :1             NA's   :51                     NA's   :2324            
 new_deaths_per_million new_deaths_smoothed_per_million reproduction_rate
 Min.   :  0.000        Min.   :  0.000                 Min.   :0.010    
 1st Qu.:  0.000        1st Qu.:  0.000                 1st Qu.:0.800    
 Median :  0.000        Median :  0.028                 Median :0.990    
 Mean   :  1.199        Mean   :  1.204                 Mean   :0.993    
 3rd Qu.:  0.000        3rd Qu.:  0.943                 3rd Qu.:1.170    
 Max.   :906.413        Max.   :129.488                 Max.   :3.610    
                        NA's   :50                      NA's   :3309     
  icu_patients   icu_patients_per_million hosp_patients   
 Min.   :    1   Min.   :  0.398          Min.   :    10  
 1st Qu.: 2736   1st Qu.: 10.100          1st Qu.: 20417  
 Median : 7383   Median : 25.064          Median : 33788  
 Mean   : 9215   Mean   : 30.441          Mean   : 41429  
 3rd Qu.:14354   3rd Qu.: 46.804          3rd Qu.: 53240  
 Max.   :28891   Max.   :128.603          Max.   :154497  
 NA's   :9866    NA's   :9866             NA's   :9874    
 hosp_patients_per_million weekly_icu_admissions
 Min.   :  1.991           Min.   :  0.00       
 1st Qu.: 67.112           1st Qu.:  4.00       
 Median :104.041           Median : 13.00       
 Mean   :134.260           Mean   : 40.24       
 3rd Qu.:169.475           3rd Qu.: 47.00       
 Max.   :456.700           Max.   :416.00       
 NA's   :9874              NA's   :10621        
 weekly_icu_admissions_per_million weekly_hosp_admissions
 Min.   :  0.000                   Min.   :     0        
 1st Qu.:  0.988                   1st Qu.:  1626        
 Median :  3.953                   Median : 30502        
 Mean   : 18.550                   Mean   : 34863        
 3rd Qu.: 12.795                   3rd Qu.: 44621        
 Max.   :224.976                   Max.   :153977        
 NA's   :10621                     NA's   :9727          
 weekly_hosp_admissions_per_million  total_tests          new_tests      
 Min.   :  0.00                     Min.   :       18   Min.   :      1  
 1st Qu.: 70.84                     1st Qu.:   216530   1st Qu.:   1250  
 Median :105.14                     Median :   802773   Median :   5533  
 Mean   :132.97                     Mean   : 74339551   Mean   : 208876  
 3rd Qu.:164.20                     3rd Qu.:  6756423   3rd Qu.:  21492  
 Max.   :643.47                     Max.   :912769124   Max.   :3201706  
 NA's   :9727                       NA's   :6175        NA's   :6423     
 total_tests_per_thousand new_tests_per_thousand new_tests_smoothed
 Min.   :   0.001         Min.   : 0.000         Min.   :      2   
 1st Qu.:  34.026         1st Qu.: 0.230         1st Qu.:    903   
 Median : 185.182         Median : 1.180         Median :   1980   
 Mean   : 709.132         Mean   : 2.214         Mean   : 164574   
 3rd Qu.:1195.669         3rd Qu.: 3.199         3rd Qu.:  16655   
 Max.   :3876.137         Max.   :29.337         Max.   :2623648   
 NA's   :6175             NA's   :6423           NA's   :5216      
 new_tests_smoothed_per_thousand positive_rate   tests_per_case   
 Min.   : 0.000                  Min.   :0.000   Min.   :   1.30  
 1st Qu.: 0.113                  1st Qu.:0.017   1st Qu.:   9.40  
 Median : 0.633                  Median :0.048   Median :  20.20  
 Mean   : 1.776                  Mean   :0.081   Mean   :  63.85  
 3rd Qu.: 2.848                  3rd Qu.:0.104   3rd Qu.:  55.60  
 Max.   :19.201                  Max.   :0.794   Max.   :5097.90  
 NA's   :5216                    NA's   :5211    NA's   :5324     
 tests_units        total_vaccinations  people_vaccinated  
 Length:10920       Min.   :        0   Min.   :        0  
 Class :character   1st Qu.:  1541747   1st Qu.:   898117  
 Mode  :character   Median : 10419337   Median :  4046334  
                    Mean   :114738743   Mean   : 52383611  
                    3rd Qu.: 42172341   3rd Qu.: 10711325  
                    Max.   :666952241   Max.   :268541239  
                    NA's   :7867        NA's   :7845       
 people_fully_vaccinated total_boosters      new_vaccinations 
 Min.   :        1       Min.   :        1   Min.   :      1  
 1st Qu.:   753903       1st Qu.:     2844   1st Qu.:   2444  
 Median :  3922126       Median :  2697006   Median :  14610  
 Mean   : 46237721       Mean   : 17202289   Mean   : 265819  
 3rd Qu.:  9999162       3rd Qu.:  7366983   3rd Qu.: 211308  
 Max.   :229580638       Max.   :133062763   Max.   :4581777  
 NA's   :7962            NA's   :8908        NA's   :8225     
 new_vaccinations_smoothed total_vaccinations_per_hundred
 Min.   :      0           Min.   :  0.00                
 1st Qu.:    316           1st Qu.: 37.62                
 Median :   3504           Median :138.47                
 Mean   : 117879           Mean   :135.73                
 3rd Qu.:  16154           3rd Qu.:200.71                
 Max.   :3508126           Max.   :380.95                
 NA's   :4708              NA's   :7867                  
 people_vaccinated_per_hundred people_fully_vaccinated_per_hundred
 Min.   :  0.00                Min.   :  0.00                     
 1st Qu.: 23.23                1st Qu.: 18.86                     
 Median : 70.21                Median : 63.40                     
 Mean   : 54.93                Mean   : 50.49                     
 3rd Qu.: 80.71                3rd Qu.: 77.21                     
 Max.   :100.00                Max.   :100.00                     
 NA's   :7845                  NA's   :7962                       
 total_boosters_per_hundred new_vaccinations_smoothed_per_million
 Min.   : 0.000             Min.   :    0                        
 1st Qu.: 0.218             1st Qu.:  227                        
 Median :27.920             Median :  762                        
 Mean   :29.452             Mean   : 2177                        
 3rd Qu.:57.835             3rd Qu.: 2611                        
 Max.   :77.370             Max.   :28708                        
 NA's   :8908               NA's   :4708                         
 new_people_vaccinated_smoothed new_people_vaccinated_smoothed_per_hundred
 Min.   :      0                Min.   :0.000                             
 1st Qu.:     73                1st Qu.:0.003                             
 Median :    925                Median :0.023                             
 Mean   :  46797                Mean   :0.078                             
 3rd Qu.:   5380                3rd Qu.:0.077                             
 Max.   :2017866                Max.   :1.778                             
 NA's   :4689                   NA's   :4689                              
   population        excess_mortality_cumulative_absolute
 Min.   :       47   Min.   : -14791                     
 1st Qu.:  1341298   1st Qu.:   1266                     
 Median :  3795066   Median :   4567                     
 Mean   : 38954262   Mean   : 198475                     
 3rd Qu.: 11212198   3rd Qu.: 131678                     
 Max.   :338289856   Max.   :1241512                     
                     NA's   :10392                       
 excess_mortality_cumulative excess_mortality
 Min.   :-9.580              Min.   :-20.42  
 1st Qu.: 5.120              1st Qu.:  1.02  
 Median : 7.050              Median :  8.27  
 Mean   : 7.589              Mean   : 11.41  
 3rd Qu.:12.835              3rd Qu.: 17.03  
 Max.   :25.520              Max.   :194.86  
 NA's   :10392               NA's   :10392   
 excess_mortality_cumulative_per_million
 Min.   :-568.3                         
 1st Qu.: 253.0                         
 Median : 956.9                         
 Mean   :1526.5                         
 3rd Qu.:2770.0                         
 Max.   :5195.8                         
 NA's   :10392                          </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 271303</code></pre>
</div>
</div>
</section>
<section id="checking-for-null-values-in-country_metadata" class="level3">
<h3 class="anchored" data-anchor-id="checking-for-null-values-in-country_metadata">3.2.2 Checking for null values in country_metadata</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   location         stringency_index population_density   median_age   
 Length:10          Min.   :0        Min.   :  3.078    Min.   :18.00  
 Class :character   1st Qu.:0        1st Qu.: 34.509    1st Qu.:19.07  
 Mode  :character   Median :0        Median : 78.525    Median :30.15  
                    Mean   :0        Mean   : 84.780    Mean   :30.19  
                    3rd Qu.:0        3rd Qu.:118.647    3rd Qu.:39.80  
                    Max.   :0        Max.   :197.519    Max.   :43.90  
                    NA's   :2        NA's   :2          NA's   :2      
 aged_65_older    aged_70_older    gdp_per_capita  extreme_poverty
 Min.   : 2.839   Min.   : 1.525   Min.   : 1095   Min.   : 0.20  
 1st Qu.: 3.409   1st Qu.: 1.869   1st Qu.: 4000   1st Qu.: 0.95  
 Median : 8.742   Median : 5.381   Median : 9542   Median :13.40  
 Mean   : 9.595   Mean   : 6.194   Mean   :23609   Mean   :23.77  
 3rd Qu.:14.907   3rd Qu.: 9.722   3rd Qu.:39645   3rd Qu.:39.75  
 Max.   :19.754   Max.   :14.136   Max.   :67335   Max.   :71.40  
 NA's   :2        NA's   :2        NA's   :3       NA's   :3      
 cardiovasc_death_rate diabetes_prevalence female_smokers    male_smokers  
 Min.   :126.5         Min.   : 3.280      Min.   : 0.900   Min.   :14.20  
 1st Qu.:181.0         1st Qu.: 3.940      1st Qu.: 5.825   1st Qu.:24.68  
 Median :235.6         Median : 5.530      Median :13.400   Median :29.95  
 Mean   :238.1         Mean   : 6.018      Mean   :13.262   Mean   :38.23  
 3rd Qu.:293.9         3rd Qu.: 7.213      3rd Qu.:20.075   3rd Qu.:51.58  
 Max.   :350.1         Max.   :10.790      Max.   :25.600   Max.   :78.10  
 NA's   :2             NA's   :2           NA's   :2        NA's   :2      
 handwashing_facilities hospital_beds_per_thousand life_expectancy
 Min.   : 8.704         Min.   :0.700              Min.   :61.04  
 1st Qu.:10.475         1st Qu.:2.035              1st Qu.:64.26  
 Median :28.178         Median :2.960              Median :74.16  
 Mean   :35.431         Mean   :3.486              Mean   :71.99  
 3rd Qu.:44.600         3rd Qu.:5.385              3rd Qu.:78.80  
 Max.   :85.198         Max.   :5.900              Max.   :82.30  
 NA's   :5              NA's   :3                  NA's   :1      
 human_development_index
 Min.   :0.4830         
 1st Qu.:0.5833         
 Median :0.7145         
 Mean   :0.7225         
 3rd Qu.:0.8810         
 Max.   :0.9550         
 NA's   :2              </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35</code></pre>
</div>
</div>
</section>
<section id="imputing-the-missing-numeric-values-with-mean" class="level3">
<h3 class="anchored" data-anchor-id="imputing-the-missing-numeric-values-with-mean">3.2.3 Imputing the missing numeric values with mean</h3>
<section id="imputing-the-missing-categorical-values-with-mode" class="level4">
<h4 class="anchored" data-anchor-id="imputing-the-missing-categorical-values-with-mode">Imputing the missing categorical values with mode</h4>
</section>
<section id="checking-again-for-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="checking-again-for-missing-values">Checking again for missing values</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   iso_code          continent           location             date          
 Length:10920       Length:10920       Length:10920       Length:10920      
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
  total_cases         new_cases       new_cases_smoothed  total_deaths    
 Min.   :       1   Min.   :      0   Min.   :     0.0   Min.   :      1  
 1st Qu.:    4649   1st Qu.:      0   1st Qu.:     0.1   1st Qu.:    137  
 Median :   84077   Median :      0   Median :    19.4   Median :   3350  
 Mean   : 5073294   Mean   :   9444   Mean   :  9487.0   Mean   :  75589  
 3rd Qu.: 1516849   3rd Qu.:      0   3rd Qu.:   453.3   3rd Qu.:  75589  
 Max.   :99019493   Max.   :5650933   Max.   :807276.1   Max.   :1079976  
   new_deaths      new_deaths_smoothed total_cases_per_million
 Min.   :    0.0   Min.   :   0.000    Min.   :     0         
 1st Qu.:    0.0   1st Qu.:   0.000    1st Qu.:  2946         
 Median :    0.0   Median :   0.143    Median : 19792         
 Mean   :  101.8   Mean   : 102.222    Mean   : 68018         
 3rd Qu.:    0.0   3rd Qu.:   4.286    3rd Qu.: 68018         
 Max.   :23312.0   Max.   :3330.286    Max.   :524420         
 new_cases_per_million new_cases_smoothed_per_million total_deaths_per_million
 Min.   :    0.0       Min.   :    0.000              Min.   :   0.003        
 1st Qu.:    0.0       1st Qu.:    0.107              1st Qu.:  90.957        
 Median :    0.0       Median :    4.217              Median : 760.689        
 Mean   :  160.1       Mean   :  160.848              Mean   : 769.290        
 3rd Qu.:    0.0       3rd Qu.:   99.142              3rd Qu.: 992.463        
 Max.   :85106.4       Max.   :12158.055              Max.   :3788.390        
 new_deaths_per_million new_deaths_smoothed_per_million reproduction_rate
 Min.   :  0.000        Min.   :  0.000                 Min.   :0.0100   
 1st Qu.:  0.000        1st Qu.:  0.000                 1st Qu.:0.8900   
 Median :  0.000        Median :  0.028                 Median :0.9931   
 Mean   :  1.199        Mean   :  1.204                 Mean   :0.9931   
 3rd Qu.:  0.000        3rd Qu.:  0.960                 3rd Qu.:1.0800   
 Max.   :906.413        Max.   :129.488                 Max.   :3.6100   
  icu_patients   icu_patients_per_million hosp_patients   
 Min.   :    1   Min.   :  0.398          Min.   :    10  
 1st Qu.: 9215   1st Qu.: 30.441          1st Qu.: 41429  
 Median : 9215   Median : 30.441          Median : 41429  
 Mean   : 9215   Mean   : 30.441          Mean   : 41429  
 3rd Qu.: 9215   3rd Qu.: 30.441          3rd Qu.: 41429  
 Max.   :28891   Max.   :128.603          Max.   :154497  
 hosp_patients_per_million weekly_icu_admissions
 Min.   :  1.991           Min.   :  0.00       
 1st Qu.:134.260           1st Qu.: 40.24       
 Median :134.260           Median : 40.24       
 Mean   :134.260           Mean   : 40.24       
 3rd Qu.:134.260           3rd Qu.: 40.24       
 Max.   :456.700           Max.   :416.00       
 weekly_icu_admissions_per_million weekly_hosp_admissions
 Min.   :  0.00                    Min.   :     0        
 1st Qu.: 18.55                    1st Qu.: 34863        
 Median : 18.55                    Median : 34863        
 Mean   : 18.55                    Mean   : 34863        
 3rd Qu.: 18.55                    3rd Qu.: 34863        
 Max.   :224.98                    Max.   :153977        
 weekly_hosp_admissions_per_million  total_tests          new_tests      
 Min.   :  0.0                      Min.   :       18   Min.   :      1  
 1st Qu.:133.0                      1st Qu.:  1763985   1st Qu.:  11724  
 Median :133.0                      Median : 74339551   Median : 208876  
 Mean   :133.0                      Mean   : 74339551   Mean   : 208876  
 3rd Qu.:133.0                      3rd Qu.: 74339551   3rd Qu.: 208876  
 Max.   :643.5                      Max.   :912769124   Max.   :3201706  
 total_tests_per_thousand new_tests_per_thousand new_tests_smoothed
 Min.   :   0.001         Min.   : 0.000         Min.   :      2   
 1st Qu.: 304.942         1st Qu.: 1.983         1st Qu.:   1810   
 Median : 709.132         Median : 2.214         Median : 164574   
 Mean   : 709.132         Mean   : 2.214         Mean   : 164574   
 3rd Qu.: 709.132         3rd Qu.: 2.214         3rd Qu.: 164574   
 Max.   :3876.137         Max.   :29.337         Max.   :2623648   
 new_tests_smoothed_per_thousand positive_rate     tests_per_case   
 Min.   : 0.000                  Min.   :0.00000   Min.   :   1.30  
 1st Qu.: 0.579                  1st Qu.:0.04510   1st Qu.:  20.00  
 Median : 1.776                  Median :0.08064   Median :  63.85  
 Mean   : 1.776                  Mean   :0.08064   Mean   :  63.85  
 3rd Qu.: 1.776                  3rd Qu.:0.08064   3rd Qu.:  63.85  
 Max.   :19.201                  Max.   :0.79440   Max.   :5097.90  
 tests_units        total_vaccinations  people_vaccinated  
 Length:10920       Min.   :        0   Min.   :        0  
 Class :character   1st Qu.:114738743   1st Qu.: 52383611  
 Mode  :character   Median :114738743   Median : 52383611  
                    Mean   :114738743   Mean   : 52383611  
                    3rd Qu.:114738743   3rd Qu.: 52383611  
                    Max.   :666952241   Max.   :268541239  
 people_fully_vaccinated total_boosters      new_vaccinations 
 Min.   :        1       Min.   :        1   Min.   :      1  
 1st Qu.: 46237721       1st Qu.: 17202289   1st Qu.: 265819  
 Median : 46237721       Median : 17202289   Median : 265819  
 Mean   : 46237721       Mean   : 17202289   Mean   : 265819  
 3rd Qu.: 46237721       3rd Qu.: 17202289   3rd Qu.: 265819  
 Max.   :229580638       Max.   :133062763   Max.   :4581777  
 new_vaccinations_smoothed total_vaccinations_per_hundred
 Min.   :      0           Min.   :  0.0                 
 1st Qu.:   2418           1st Qu.:135.7                 
 Median : 117879           Median :135.7                 
 Mean   : 117879           Mean   :135.7                 
 3rd Qu.: 117879           3rd Qu.:135.7                 
 Max.   :3508126           Max.   :380.9                 
 people_vaccinated_per_hundred people_fully_vaccinated_per_hundred
 Min.   :  0.00                Min.   :  0.00                     
 1st Qu.: 54.93                1st Qu.: 50.49                     
 Median : 54.93                Median : 50.49                     
 Mean   : 54.93                Mean   : 50.49                     
 3rd Qu.: 54.93                3rd Qu.: 50.49                     
 Max.   :100.00                Max.   :100.00                     
 total_boosters_per_hundred new_vaccinations_smoothed_per_million
 Min.   : 0.00              Min.   :    0                        
 1st Qu.:29.45              1st Qu.:  602                        
 Median :29.45              Median : 2177                        
 Mean   :29.45              Mean   : 2177                        
 3rd Qu.:29.45              3rd Qu.: 2177                        
 Max.   :77.37              Max.   :28708                        
 new_people_vaccinated_smoothed new_people_vaccinated_smoothed_per_hundred
 Min.   :      0                Min.   :0.00000                           
 1st Qu.:    597                1st Qu.:0.01700                           
 Median :  38126                Median :0.07791                           
 Mean   :  46797                Mean   :0.07791                           
 3rd Qu.:  46797                3rd Qu.:0.07791                           
 Max.   :2017866                Max.   :1.77800                           
   population        excess_mortality_cumulative_absolute
 Min.   :       47   Min.   : -14791                     
 1st Qu.:  1341298   1st Qu.: 198475                     
 Median :  3795066   Median : 198475                     
 Mean   : 38954262   Mean   : 198475                     
 3rd Qu.: 11212198   3rd Qu.: 198475                     
 Max.   :338289856   Max.   :1241512                     
 excess_mortality_cumulative excess_mortality
 Min.   :-9.580              Min.   :-20.42  
 1st Qu.: 7.589              1st Qu.: 11.41  
 Median : 7.589              Median : 11.41  
 Mean   : 7.589              Mean   : 11.41  
 3rd Qu.: 7.589              3rd Qu.: 11.41  
 Max.   :25.520              Max.   :194.86  
 excess_mortality_cumulative_per_million
 Min.   :-568.3                         
 1st Qu.:1526.5                         
 Median :1526.5                         
 Mean   :1526.5                         
 3rd Qu.:1526.5                         
 Max.   :5195.8                         </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
</section>
<section id="handling-missing-values-in-the-country-metadata-file" class="level3">
<h3 class="anchored" data-anchor-id="handling-missing-values-in-the-country-metadata-file">3.2.4 Handling missing values in the country metadata file</h3>
<section id="imputing-the-missing-numeric-values-with-mean-1" class="level4">
<h4 class="anchored" data-anchor-id="imputing-the-missing-numeric-values-with-mean-1">Imputing the missing numeric values with mean</h4>
</section>
<section id="imputing-the-missing-categorical-values-with-mode-for-location" class="level4">
<h4 class="anchored" data-anchor-id="imputing-the-missing-categorical-values-with-mode-for-location">Imputing the missing categorical values with mode (for ‘location’)</h4>
</section>
<section id="checking-again-for-missing-values-1" class="level4">
<h4 class="anchored" data-anchor-id="checking-again-for-missing-values-1">Checking again for missing values</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   location         stringency_index population_density   median_age   
 Length:10          Min.   :0        Min.   :  3.078    Min.   :18.00  
 Class :character   1st Qu.:0        1st Qu.: 44.175    1st Qu.:20.05  
 Mode  :character   Median :0        Median : 84.780    Median :30.19  
                    Mean   :0        Mean   : 84.780    Mean   :30.19  
                    3rd Qu.:0        3rd Qu.:104.600    3rd Qu.:38.60  
                    Max.   :0        Max.   :197.519    Max.   :43.90  
 aged_65_older    aged_70_older    gdp_per_capita  extreme_poverty
 Min.   : 2.839   Min.   : 1.525   Min.   : 1095   Min.   : 0.20  
 1st Qu.: 3.553   1st Qu.: 1.944   1st Qu.: 7313   1st Qu.: 4.25  
 Median : 9.595   Median : 6.194   Median :23609   Median :23.77  
 Mean   : 9.595   Mean   : 6.194   Mean   :23609   Mean   :23.77  
 3rd Qu.:14.536   3rd Qu.: 9.459   3rd Qu.:24700   3rd Qu.:28.67  
 Max.   :19.754   Max.   :14.136   Max.   :67335   Max.   :71.40  
 cardiovasc_death_rate diabetes_prevalence female_smokers   male_smokers  
 Min.   :126.5         Min.   : 3.280      Min.   : 0.90   Min.   :14.20  
 1st Qu.:200.1         1st Qu.: 4.183      1st Qu.: 7.15   1st Qu.:24.95  
 Median :238.1         Median : 6.018      Median :13.26   Median :36.21  
 Mean   :238.1         Mean   : 6.018      Mean   :13.26   Mean   :38.23  
 3rd Qu.:271.0         3rd Qu.: 6.683      3rd Qu.:18.60   3rd Qu.:47.81  
 Max.   :350.1         Max.   :10.790      Max.   :25.60   Max.   :78.10  
 handwashing_facilities hospital_beds_per_thousand life_expectancy
 Min.   : 8.704         Min.   :0.700              Min.   :61.04  
 1st Qu.:29.991         1st Qu.:2.817              1st Qu.:65.57  
 Median :35.431         Median :3.486              Median :73.08  
 Mean   :35.431         Mean   :3.486              Mean   :71.99  
 3rd Qu.:35.431         3rd Qu.:4.771              3rd Qu.:77.92  
 Max.   :85.198         Max.   :5.900              Max.   :82.30  
 human_development_index
 Min.   :0.4830         
 1st Qu.:0.6160         
 Median :0.7225         
 Mean   :0.7225         
 3rd Qu.:0.8452         
 Max.   :0.9550         </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>The null values in both datasets have been checked using the ‘is.na(country_data)’ and ‘is.na(country_metadata)’ functions respectively. According to Palanivinayagam and Damaševičius (2023), null values in the dataset cause data inconsistency, as it can cause inaccurate data analysis. The observed null values in the ‘country_data’ and ‘country_metadata’ datasets are 271303 and 35 respectively. The null values in the numerical columns have been replaced with the respective column mean, while null values in categorical columns are replaced with mode, leading to the elimination of data inconsistency in the datasets. The main reason for replacing null values in numerical columns with mean is to retain the overall central tendency of the distribution, while, replacement of missing values with mode has ensured categorical balance by representing the most frequent category.</p>
</section>
</section>
</section>
<section id="data-selection" class="level2">
<h2 class="anchored" data-anchor-id="data-selection">3.3 Data selection</h2>
<p>Through the use of the ‘aggregate function’ in R relevant variables (such as continent, location, date, total_cases, new_cases, total_deaths, new_deaths, total_cases_per_million, and total_deaths_per_million) have been selected from the dataset.</p>
</section>
<section id="summarise-and-filtering" class="level2">
<h2 class="anchored" data-anchor-id="summarise-and-filtering">3.4 Summarise and Filtering</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   location      total_cases total_deaths
   &lt;chr&gt;               &lt;dbl&gt;        &lt;dbl&gt;
 1 Cuba             5073294.       75589.
 2 Ireland          5073294.       75589.
 3 Latvia           5073294.       75589.
 4 Malawi           5073294.       75589.
 5 Montserrat       5073294.       75589.
 6 Namibia          5073294.       75589.
 7 Pitcairn         5073294.       75589.
 8 Timor            5073294.       75589.
 9 Togo             5073294.       75589.
10 United States   99019493      1079976 </code></pre>
</div>
</div>
<p>The ‘group_by (location’ function has grouped the data by location column, helping in effectively creating a subset for each unique location. On the subset, the ‘summarize ()’ function has been used to calculate the ‘total_cases’ and ‘total_deaths’ for Ireland and 9 other countries. Additionally, the use of the ‘max ()’ has ensured the capturing of the latest cumulative totals for Covid-19 cases and deaths up to the recent date available in the dataset.</p>
<p>From the summary table, it can be observed that the total Covid-19 cases and deaths from 2020 to 2022 in the United States were 99019493 and 1079976 respectively, whereas in Ireland the same (total Covid-19 cases and deaths) were 5073294 and 75589 respectively. This shows that the severity of Covid-19 was considerably lower in Ireland, compared to the United States.</p>
<section id="filter-data-for-ireland-and-9-other-countries" class="level3">
<h3 class="anchored" data-anchor-id="filter-data-for-ireland-and-9-other-countries">3.4.1 Filter data for Ireland and 9 other countries</h3>
</section>
</section>
</section>
<section id="visualisation" class="level1">
<h1>4. Visualisation</h1>
<section id="world-map-chart-of-total-covid-19-cases" class="level2">
<h2 class="anchored" data-anchor-id="world-map-chart-of-total-covid-19-cases">4.1 World Map Chart of Total Covid 19 cases</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MT5000-Quarto-Report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Figure 1: World map chart</em></strong></p>
<p>The world map visualises Covid-19 total cases by country, where the larger and brighter circles indicate higher population density [<strong><em>Refer to Figure 1</em></strong>]. The United States has the highest total cases, significantly higher than other countries like Ireland, Cuba, Latvia, Montserrat, Namibia, Pitcairn, Togo, Timor and Malawi. On the other hand, irrespective of high population density, total covid cases in Ireland were considerably low, signifying the positive effects of government interventions such as prohibition of public gatherings and shutting off non-essential shops and local community centres (O’leary et al., 2021). However, irrespective of low population density, the existence of higher cases relative to population density has been observed, highlighting the high severity of the pandemic in the US compared to other countries.</p>
</section>
<section id="bar-chart-showing-total-cases-across-countries" class="level2">
<h2 class="anchored" data-anchor-id="bar-chart-showing-total-cases-across-countries">4.2 Bar Chart showing total cases across countries</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MT5000-Quarto-Report_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Figure 2: Bar chart showing total Covid-19 cases across countries</em></strong></p>
<p>The bar chart demonstrates the total cases of Covid-19 cases across the 10 countries, from where it can be observed that the United States had a significantly higher number of cases (approximately 99 million) [<strong><em>Refer to Figure 2</em></strong>]. Additionally, Ireland exhibited a case count of 1.689 million among smaller nations, indicating a significant spread in spite of having a smaller population. On the other hand, total cases in countries like Togo (0.039 million), Timor (0.023 million), Montserrat (0.0014 million) and Pitcairn (0.000004 million) were considerably lower than the United States and Ireland.</p>
</section>
<section id="scatterplot-with-a-linear-regression-line-for-covid-19-total-deaths-vs-total-cases" class="level2">
<h2 class="anchored" data-anchor-id="scatterplot-with-a-linear-regression-line-for-covid-19-total-deaths-vs-total-cases">4.3 Scatterplot with a linear regression line for COVID-19 Total Deaths vs Total Cases</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MT5000-Quarto-Report_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Figure 3: Scatter plot showing Covid-19 total deaths versus total cases</em></strong></p>
<p>The scatter plot demonstrates the variation in total deaths with total cases, from which it can be observed that in Countries like the United States, a linearly increasing pattern has been observed [<strong><em>Refer to Figure 3</em></strong>]. This indicates that with an increase in total cases, the number of deaths has increased in the United States. On the other hand, in countries like Ireland, total death cases are considerably low as observed in the Scatter plot. In this context, a report published by the Central Statistics Office in Ireland, that total daily deaths due to Covid-19 from 2020 to 2022 ranged from 57 to 75, supporting a low death rate in Ireland (Central Statistics Office, 2023). In fact, a similar trend has been observed in countries like Malawi, Montserrat, Namibia, Timor, Togo and Pitcairn.</p>
</section>
<section id="time-series-plot-for-new-cases-across-countries-over-the-periods-2020-2022" class="level2">
<h2 class="anchored" data-anchor-id="time-series-plot-for-new-cases-across-countries-over-the-periods-2020-2022">4.4 Time Series plot for new cases across countries over the periods (2020-2022)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MT5000-Quarto-Report_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong><em>Figure 4: Time series plot showing new Covid-19 cases over time (2020 to 2022)</em></strong></p>
<p>The time series plot represents the trend of new Covid-19 cases over time (2020 to 2022) for Ireland along with 9 other countries, where the y-axis indicates the number of new cases and the x-axis indicates the timeline. Smaller peaks have been observed around mid-2020 in countries like the United States, representing the initial outbreak of Covid-19 [<strong><em>Refer to Figure 4</em></strong>]. However, major peaks have been observed from late 2020 to early 2021, indicating the highest spike in the occurrence of Covid-19, mainly due to the spread of SARS-CoV-2 variants.</p>
</section>
</section>
<section id="conclusions" class="level1">
<h1>5. Conclusions</h1>
<p>Based on the analysis, it can be summarised that the severity of covid-19 in Ireland was significantly lower than in countries like the United States and Cuba. On the other hand, the occurrence of new Covid-19 cases and death rates were similar for countries Togo, Malawi, Pitcairn and Timor. The implementation of government interventions like strict prohibition on social gatherings and vaccination has allowed the authorities in Ireland to keep the pandemic under control.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Central Statistics Office (2023) COVID-19 Deaths and Cases Statistics - CSO - Central Statistics Office, www.cso.ie. Central Statistics Office. Available at: https://www.cso.ie/en/statistics/health/covid-19deathsandcasesstatistics/ (Accessed: 20 June 2024).</p>
<p>Elflein, J. (2022) Coronavirus (COVID-19) cumulative cases by day U.S. 2020, Statista. www.statista.com. Available at: https://www.statista.com/statistics/1103185/cumulative-coronavirus-covid19-cases-number-us-by-day/ (Accessed: 20 June 2024).</p>
<p>Elflein, J. (2023) Novel coronavirus (COVID-19) deaths by country worldwide 2020, Statista. www.statista.com. Available at: https://www.statista.com/statistics/1093256/novel-coronavirus-2019ncov-deaths-worldwide-by-country/ (Accessed: 20 June 2024).</p>
<p>Gagliardi, J. (2023) Number of coronavirus (COVID-19) cases in Ireland since February 2020, Statista. www.statista.com. Available at: https://www.statista.com/statistics/1107064/coronavirus-cases-development-ireland/ (Accessed: 20 June 2024).</p>
<p>O’leary, N. et al.&nbsp;(2021) ‘COVID-19 healthcare policies in Ireland: A rapid review of the initial pandemic response’, Scandinavian Journal of Public Health, 49(7), pp.&nbsp;713–720. doi: https://doi.org/10.1177/14034948211008371.</p>
<p>Palanivinayagam, A. and Damaševičius, R. (2023) ‘Effective Handling of Missing Values in Datasets for Classification Using Machine Learning Methods’, Information, 14(2), p.&nbsp;92. doi: https://doi.org/10.3390/info14020092.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>